# Generated by Django 4.1.6 on 2023-02-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="blog",
            new_name="Post",
        ),
    ]
